### ISSUE TITLE
Deprecated call: Ember Resolver

### ISSUE THREAD

**Issue by adambullmer** [sglanzer/ember-cli-blanket#12]
Pretty sure it's originating from this repo. Getting a deprecation notice.

```
 DEPRECATION: Importing/requiring Ember Resolver as "resolver" is deprecated, please use "ember/resolver" instead
        at http://localhost:4200/assets/vendor.js:63265:11
        at requireModule (http://localhost:4200/assets/vendor.js:77:29)
        at oldLoader (http://localhost:4200/assets/blanket-loader.js:31:13)
        at Object._blanket.extend.utils.processFile (http://localhost:4200/assets/test-support.js:8107:17)
        at blanketLoader (http://localhost:4200/assets/blanket-loader.js:24:19)
        at http://localhost:4200/assets/blanket-loader.js:45:23
```

**Comment by sglanzer** [comment]
@adambullmer @notmessenger I've upgraded the project to ember-cli 0.1.12 and I've removed a lot of dependencies that were part of the ember addon generation.  This issue should be resolved in the 0.2.3 release.
