### ISSUE TITLE
Running tests with no coverage throwing an error `Cannot read property 'map' of undefined`

### ISSUE THREAD

**Issue by dafortin** [sglanzer/ember-cli-blanket#134]
I added ember-cli-blanket to my new project. I'm seeing the coverage when I'm using the following url: http://localhost:4200/tests?coverage. There is not errors in my terminal. 

When I'm using the following url: http://localhost:4200/tests (Run the tests with no coverage) 

I'm seeing an error in my browser (chrome): `jquery.js:9203 POST http://localhost:4200/write-blanket-coverage 500 (Internal Server Error)`

I'm also seeing an error in my terminal running my ember server: 
`TypeError: Cannot read property 'map' of undefined
    at Reporter.module.exports.Reporter.extend.transform (/Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/reporters/lcov-reporter.js:40:37)
    at Reporter.report (/Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/reporter.js:51:21)
    at /Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/coverage-middleware.js:37:16
    at arrayEach (/Users/dafortin/code/frost-label-svg/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/dafortin/code/frost-label-svg/node_modules/lodash/index.js:3345:13)
    at /Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/coverage-middleware.js:36:7
    at Layer.handle [as handle_request] (/Users/dafortin/code/frost-label-svg/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/dafortin/code/frost-label-svg/node_modules/express/lib/router/route.js:131:13)
    at /Users/dafortin/code/frost-label-svg/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Users/dafortin/code/frost-label-svg/node_modules/raw-body/index.js:262:16)
TypeError: Cannot read property 'map' of undefined
    at Reporter.module.exports.Reporter.extend.transform (/Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/reporters/lcov-reporter.js:40:37)
    at Reporter.report (/Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/reporter.js:51:21)
    at /Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/coverage-middleware.js:37:16
    at arrayEach (/Users/dafortin/code/frost-label-svg/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/dafortin/code/frost-label-svg/node_modules/lodash/index.js:3345:13)
    at /Users/dafortin/code/frost-label-svg/node_modules/ember-cli-blanket/lib/coverage-middleware.js:36:7
    at Layer.handle [as handle_request] (/Users/dafortin/code/frost-label-svg/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/dafortin/code/frost-label-svg/node_modules/express/lib/router/route.js:131:13)
    at /Users/dafortin/code/frost-label-svg/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Users/dafortin/code/frost-label-svg/node_modules/raw-body/index.js:262:16)`

**Comment by jschilli** [comment]
That was a regression - fixed in #133 

not yet release but feel free to verify against that commit.
