### ISSUE TITLE
Cannot run tests with LCOV reporter

### ISSUE THREAD

**Issue by green-arrow** [sglanzer/ember-cli-blanket#57]
Whenever I attempt to run `ember test` or `ember test --server`, and have the reporter set to `lcov` instead of `json`, I run into the following error:

```bash
TypeError: Cannot read property 'map' of undefined
    at Reporter.module.exports.Reporter.extend.transform (/Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli-blanket/lib/reporters/lcov-reporter.js:27:37)
    at Reporter.report (/Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli-blanket/lib/reporter.js:51:21)
    at /Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli-blanket/lib/coverage-middleware.js:39:16
    at Layer.handle [as handle_request] (/Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli/node_modules/express/lib/router/index.js:302:13)
    at /Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli/node_modules/express/lib/router/index.js:261:10)
    at /Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli-blanket/node_modules/body-parser/lib/read.js:111:5
    at IncomingMessage.onEnd (/Users/green-arrow/Documents/Github/Cordata/navigator-ui/node_modules/ember-cli-blanket/node_modules/body-parser/node_modules/raw-body/index.js:149:7)
```

FWIW, I'm running on `node 0.12.0`. Also, it completely messes up my build directory, so I'm not able to run tests / run `ember server` afterwards until I `rm -rf dist tmp`.

**Comment by jschilli** [comment]
@green-arrow and when you run it with `json` it completes correctly and writes the json output?

what version of ember-cli-blanket?

**Comment by green-arrow** [comment]
@jschilli correct, when I run it with `json` everything works fine and I can see the correct json output.

`ember-cli-blanket 0.5.1`

**Comment by jschilli** [comment]
bizarre - I can see that lcov-reporter isn't handling errors if coverageData comes back empty

to save us from guessing, can you alter `node_modules/ember-cli-blanket/lib/coverage-middleware` locally 

after the line:
`    if (req.method === 'POST' && req.url === '/write-blanket-coverage') {` 

add `console.dir(req.body);` 

not sure if it's being called twice or mangling the data.

the client side doesn't know which reporter is invoked so double bizarre that json works and lcov does not

**Comment by green-arrow** [comment]
@jschilli this is super weird, I added that line and now I'm not getting the error anymore. Perhaps something went bad in my project. I nuked everything and pulled down a fresh copy and now the error is gone.

Appreciate the quick response!

**Comment by jschilli** [comment]
closing for now - if you see it again we'll look at it - I've taken a note to improve error handling in lcov-reporter

**Comment by justin-lau** [comment]
I'm hitting the same problem with v0.8.0 and ember-cli-mocha.

I added the `console.dir(req.body);` and it shows that the `req.body` equals to `{}`.

Tried purging everything and reinstalling bower and npm dependencies, didn't help.
